#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_BUNDLE="$ROOT_DIR/outputs/EyeRest.app"
BINARY="$APP_BUNDLE/Contents/MacOS/EyeRest"
INFO_PLIST="$APP_BUNDLE/Contents/Info.plist"
EXPECTED_VERSION="$(tr -d '[:space:]' < "$ROOT_DIR/VERSION")"
SOURCE_FILE="$ROOT_DIR/Sources/EyeRestObjC/main.m"
SMOKE_FILE="$ROOT_DIR/scripts/smoke_test.sh"

cd "$ROOT_DIR"

fail() {
  echo "preflight_release: $*" >&2
  exit 1
}

check_contains() {
  local haystack="$1"
  local needle="$2"
  local label="$3"
  if [[ "$haystack" != *"$needle"* ]]; then
    fail "$label missing: $needle"
  fi
}

plist_value() {
  local key="$1"
  /usr/libexec/PlistBuddy -c "Print :$key" "$INFO_PLIST"
}

echo "==> Checking shell scripts"
bash -n scripts/build_app.sh
bash -n scripts/diagnose_app.sh
bash -n scripts/generate_icon.sh
bash -n scripts/install_app.sh
bash -n scripts/package_app.sh
bash -n scripts/preflight_release.sh
bash -n scripts/smoke_test.sh

echo "==> Building app"
scripts/build_app.sh >/dev/null

echo "==> Verifying bundle metadata"
[[ -x "$BINARY" ]] || fail "binary is missing or not executable"
[[ -s "$APP_BUNDLE/Contents/Resources/AppIcon.icns" ]] || fail "AppIcon.icns is missing"
[[ "$(plist_value CFBundleIdentifier)" == "local.codex.eyerest" ]] || fail "bundle identifier mismatch"
[[ "$(plist_value CFBundleDisplayName)" == "松一下" ]] || fail "display name mismatch"
[[ "$(plist_value CFBundleIconFile)" == "AppIcon" ]] || fail "icon metadata mismatch"
[[ "$(plist_value CFBundleShortVersionString)" == "$EXPECTED_VERSION" ]] || fail "version mismatch"
URL_TYPES="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleURLTypes' "$INFO_PLIST")"
[[ "$URL_TYPES" == *"songyixia"* ]] || fail "URL scheme missing"

echo "==> Verifying binary entry points"
STRINGS_OUTPUT="$(strings "$BINARY")"
for selector in handleAutomationURL: runRecoveryStressTest: importBackupJSON: showAbout: openIssueFeedback: checkForUpdates: applyQuickRhythm: applyQuickRhythmToken: showQuickSetup: applyQuickSetupProfile: copyApplicationDiagnostic: applicationDiagnosticText copyDisplayDiagnostic: displayDiagnosticText copyRecoveryMatrixDiagnostic: recoveryMatrixDiagnosticText copyRecoveryReportDiagnostic: recoveryReportDiagnosticText runRecoveryMatrixSuite: runRecoveryMatrixSuiteStep: finishRecoveryMatrixSuiteWithTotal: copySupportBundleDiagnostic: supportBundleDiagnosticText copyIssueBundleDiagnostic: issueBundleDiagnosticText toggleRestWindowTopmost:; do
  check_contains "$STRINGS_OUTPUT" "$selector" "selector"
done
check_contains "$STRINGS_OUTPUT" "https://github.com/passionate11/-" "GitHub URL"
check_contains "$STRINGS_OUTPUT" "https://github.com/passionate11/-/issues/new" "GitHub issue URL"
check_contains "$STRINGS_OUTPUT" "https://github.com/passionate11/-/releases/latest" "latest release URL"
check_contains "$STRINGS_OUTPUT" "https://api.github.com/repos/passionate11/-/releases/latest" "latest release API URL"

echo "==> Verifying window behavior guardrails"
SOURCE_CONTENT="$(< "$SOURCE_FILE")"
README_CONTENT="$(< README.md)"
SMOKE_CONTENT="$(< "$SMOKE_FILE")"
check_contains "$SOURCE_CONTENT" "应用诊断" "application diagnostics title"
check_contains "$SOURCE_CONTENT" "复制版本信息" "about copy version action"
check_contains "$SOURCE_CONTENT" "反馈包链接" "issue feedback bundle link"
check_contains "$SOURCE_CONTENT" "今日概览" "settings overview page"
check_contains "$SOURCE_CONTENT" "overviewEyeTimerLabel" "settings overview eye timer"
check_contains "$SOURCE_CONTENT" "overviewStandTimerLabel" "settings overview stand timer"
check_contains "$SOURCE_CONTENT" "overviewStatusBand" "settings overview status band"
check_contains "$SOURCE_CONTENT" "overviewStatusBadgeLabel" "settings overview status badge"
check_contains "$SOURCE_CONTENT" "overviewActionBar" "settings overview action bar"
check_contains "$SOURCE_CONTENT" "NSMakeRect(0, 0, 880, 560)" "settings wide window guard"
check_contains "$SOURCE_CONTENT" "sidebarSelectionViews" "settings sidebar selection guard"
check_contains "$SOURCE_CONTENT" "refreshSidebarAppearance" "settings sidebar appearance guard"
check_contains "$SOURCE_CONTENT" "NSBezelStyleRegularSquare" "settings borderless sidebar guard"
check_contains "$SOURCE_CONTENT" "eyeSummaryBand" "eye settings summary band"
check_contains "$SOURCE_CONTENT" "standSummaryBand" "stand settings summary band"
check_contains "$SOURCE_CONTENT" "refreshTimingSummaries" "timing summary refresh helper"
check_contains "$SOURCE_CONTENT" "presentSettingsPage:" "settings page deep link helper"
check_contains "$SOURCE_CONTENT" "settings/eye" "settings eye URL"
check_contains "$SOURCE_CONTENT" "settings/stand" "settings stand URL"
check_contains "$SMOKE_CONTENT" "settings_window_visible" "settings window visible smoke helper"
check_contains "$SMOKE_CONTENT" "settings/eye did not show settings window" "settings eye visible smoke check"
check_contains "$SMOKE_CONTENT" "settings/stand did not show settings window" "settings stand visible smoke check"
check_contains "$SOURCE_CONTENT" "refreshOverview" "settings overview refresh helper"
check_contains "$SOURCE_CONTENT" "[self.settingsWindowController refreshOverview]" "settings overview live refresh"
check_contains "$SOURCE_CONTENT" "overviewRestEyeNow:" "settings overview eye action"
check_contains "$SOURCE_CONTENT" "overviewRestStandNow:" "settings overview stand action"
check_contains "$SOURCE_CONTENT" "overviewPauseThirtyMinutes:" "settings overview pause action"
check_contains "$SOURCE_CONTENT" "overviewCopyIssueBundle:" "settings overview issue bundle action"
check_contains "$SOURCE_CONTENT" "openQuickSetup:" "settings overview quick setup action"
check_contains "$SOURCE_CONTENT" "overviewQuickSetupButton" "settings overview quick setup button"
check_contains "$SOURCE_CONTENT" "pauseForSeconds:" "shared pause helper"
check_contains "$SOURCE_CONTENT" "footerView" "settings footer view"
check_contains "$SOURCE_CONTENT" "ERAddStyleMotifLayers" "shared style motif layers"
check_contains "$SOURCE_CONTENT" "settings-card-motif" "settings card motif guard"
check_contains "$SOURCE_CONTENT" "stylePreviewMotif" "style preview motif guard"
check_contains "$SOURCE_CONTENT" "rest-backdrop-motif" "rest overlay backdrop motif guard"
check_contains "$SOURCE_CONTENT" "rest-card-motif" "rest overlay card motif guard"
check_contains "$SOURCE_CONTENT" "restBackdropGradient" "rest overlay gradient guard"
check_contains "$SOURCE_CONTENT" "standStagePanel" "stand stage panel guard"
check_contains "$SOURCE_CONTENT" "standStageProgressFill" "stand stage progress guard"
check_contains "$SOURCE_CONTENT" "下一步：" "stand next action guard"
check_contains "$SOURCE_CONTENT" "settingsDarkStyle = self.settings.restStyle == ERRestStyleNight" "settings text contrast guard"
check_contains "$README_CONTENT" "今日概览" "settings overview docs"
check_contains "$README_CONTENT" "顶部状态带" "settings overview dashboard docs"
check_contains "$README_CONTENT" "设置页宽面板打磨" "settings wide panel docs"
check_contains "$README_CONTENT" "设置页侧栏选中态" "settings sidebar selected docs"
check_contains "$README_CONTENT" "songyixia://settings/eye" "settings eye URL docs"
check_contains "$README_CONTENT" "眼睛/站立设置页摘要带" "settings timing summary docs"
check_contains "$README_CONTENT" "打开快速配置" "settings overview action docs"
check_contains "$README_CONTENT" "设置页风格图案层" "settings style motif docs"
check_contains "$README_CONTENT" "休息页风格同源" "rest overlay shared style docs"
check_contains "$README_CONTENT" "站立阶段面板" "stand stage panel docs"
check_contains "$README_CONTENT" "普通用户更新链路" "user update flow docs"
check_contains "$README_CONTENT" "产品化反馈闭环" "product feedback loop docs"
check_contains "$SOURCE_CONTENT" "productSupportSummaryText" "product support summary helper"
check_contains "$SOURCE_CONTENT" "ERSettingsQuickSetupSeenKey" "quick setup seen preference"
check_contains "$SOURCE_CONTENT" "快速配置..." "quick setup menu"
check_contains "$SOURCE_CONTENT" "applyQuickSetupProfile:" "quick setup apply action"
check_contains "$SOURCE_CONTENT" "showQuickSetup:" "quick setup sheet action"
check_contains "$SOURCE_CONTENT" "setup/balanced" "quick setup balanced automation URL"
check_contains "$SOURCE_CONTENT" "setup/pomodoro" "quick setup pomodoro automation URL"
check_contains "$SOURCE_CONTENT" "setup/stand" "quick setup stand automation URL"
check_contains "$SOURCE_CONTENT" "setup/debug" "quick setup debug automation URL"
check_contains "$SOURCE_CONTENT" "均衡护眼" "quick setup balanced profile"
check_contains "$SOURCE_CONTENT" "久坐打断" "quick setup stand profile"
check_contains "$SOURCE_CONTENT" "调试 10 秒" "quick setup debug profile"
check_contains "$README_CONTENT" "songyixia://setup/debug" "quick setup automation docs"
check_contains "$README_CONTENT" "均衡护眼、番茄专注、久坐打断和调试 10 秒" "quick setup docs"
check_contains "$SOURCE_CONTENT" "applyQuickRhythm:" "quick rhythm action"
check_contains "$SOURCE_CONTENT" "quickRhythmMatchesItemInfo" "quick rhythm state guard"
check_contains "$SOURCE_CONTENT" "快速节奏" "quick rhythm menu"
check_contains "$SOURCE_CONTENT" "调试 10 秒" "debug rhythm menu item"
check_contains "$SOURCE_CONTENT" "rhythm/debug" "debug rhythm automation URL"
check_contains "$README_CONTENT" "songyixia://rhythm/debug" "debug rhythm docs"
check_contains "$SOURCE_CONTENT" "copyFocusAutomationTemplate:" "focus automation template action"
check_contains "$SOURCE_CONTENT" "focus-template" "focus automation template URL token"
check_contains "$SOURCE_CONTENT" "Hammerspoon 示例" "focus automation template content"
check_contains "$SOURCE_CONTENT" "Raycast Script Command 示例" "raycast automation template content"
check_contains "$README_CONTENT" "songyixia://automation/focus-template" "focus automation template docs"
check_contains "$SOURCE_CONTENT" "copyAutomationDiagnostic:" "automation diagnostic action"
check_contains "$SOURCE_CONTENT" "automationDiagnosticText" "automation diagnostic text helper"
check_contains "$SOURCE_CONTENT" "Bundle ID" "automation diagnostic bundle id"
check_contains "$SOURCE_CONTENT" "bundle.bundleIdentifier" "automation diagnostic bundle identifier value"
check_contains "$README_CONTENT" "songyixia://automation/diagnostic" "automation diagnostic docs"
check_contains "$SOURCE_CONTENT" "runLunchRecoveryStressTest:" "lunch recovery stress action"
check_contains "$SOURCE_CONTENT" "diagnostics/lunch-recovery" "lunch recovery automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/lunch-recovery" "lunch recovery docs"
check_contains "$SOURCE_CONTENT" "午休恢复压测" "lunch recovery diagnostics"
check_contains "$SOURCE_CONTENT" "runSleepHiddenRecoveryStressTest:" "sleep hidden recovery stress action"
check_contains "$SOURCE_CONTENT" "diagnostics/sleep-hidden-recovery" "sleep hidden recovery automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/sleep-hidden-recovery" "sleep hidden recovery docs"
check_contains "$SOURCE_CONTENT" "隐藏休息页已恢复" "sleep hidden recovery restores hidden window"
check_contains "$SOURCE_CONTENT" "已让开休息页保持隐藏" "sleep hidden recovery preserves yielded window"
check_contains "$SOURCE_CONTENT" "runLongAwayRecoveryStressTest:" "long away recovery stress action"
check_contains "$SOURCE_CONTENT" "diagnostics/long-away-recovery" "long away recovery automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/long-away-recovery" "long away recovery docs"
check_contains "$SOURCE_CONTENT" "长离开恢复压测" "long away recovery diagnostics"
check_contains "$SOURCE_CONTENT" "runDisplayRecoveryStressTest:" "display recovery stress action"
check_contains "$SOURCE_CONTENT" "diagnostics/display-recovery" "display recovery automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/display-recovery" "display recovery docs"
check_contains "$SOURCE_CONTENT" "显示恢复压测" "display recovery diagnostics"
check_contains "$SOURCE_CONTENT" "repairSettingsWindowAfterDisplayChange" "settings window display repair helper"
check_contains "$SOURCE_CONTENT" "runSettingsWindowRecoveryStressTest:" "settings window recovery stress action"
check_contains "$SOURCE_CONTENT" "diagnostics/settings-window" "settings window recovery automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/settings-window" "settings window recovery docs"
check_contains "$SOURCE_CONTENT" "设置窗口恢复压测" "settings window recovery diagnostics"
check_contains "$SOURCE_CONTENT" "设置页回到屏幕内" "settings window onscreen diagnostic"
check_contains "$SOURCE_CONTENT" "runDisplayBoundsStressTest:" "display bounds stress action"
check_contains "$SOURCE_CONTENT" "diagnostics/display-bounds" "display bounds automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/display-bounds" "display bounds docs"
check_contains "$SOURCE_CONTENT" "显示边界压测" "display bounds diagnostics"
check_contains "$SOURCE_CONTENT" "runRealDisplayCheck:" "real display check action"
check_contains "$SOURCE_CONTENT" "copyDisplayDiagnostic:" "display diagnostic action"
check_contains "$SOURCE_CONTENT" "displayDiagnosticText" "display diagnostic text helper"
check_contains "$SOURCE_CONTENT" "diagnostics/display-real" "real display diagnostic automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/display-real" "real display diagnostic docs"
check_contains "$SOURCE_CONTENT" "显示环境诊断" "real display diagnostic title"
check_contains "$SOURCE_CONTENT" "displayDiagnostic=1" "real display diagnostic machine marker"
check_contains "$SOURCE_CONTENT" "screenCount=" "real display diagnostic screen count"
check_contains "$SOURCE_CONTENT" "copyRecoveryMatrixDiagnostic:" "recovery matrix diagnostic action"
check_contains "$SOURCE_CONTENT" "recoveryMatrixDiagnosticText" "recovery matrix diagnostic text helper"
check_contains "$SOURCE_CONTENT" "diagnostics/recovery-matrix" "recovery matrix diagnostic URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/recovery-matrix" "recovery matrix diagnostic docs"
check_contains "$SOURCE_CONTENT" "runRecoveryMatrixSuite:" "recovery matrix suite action"
check_contains "$SOURCE_CONTENT" "diagnostics/recovery-matrix-suite" "recovery matrix suite automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/recovery-matrix-suite" "recovery matrix suite docs"
check_contains "$SOURCE_CONTENT" "开始 %ld 个场景顺序压测" "recovery matrix suite start marker"
check_contains "$SOURCE_CONTENT" "完成 %ld/%ld，已顺序触发全部恢复场景" "recovery matrix suite completion marker"
check_contains "$SOURCE_CONTENT" "ERRecoveryHistoryLimit = 80" "expanded recovery history limit"
check_contains "$SOURCE_CONTENT" "recoveryMatrix=1" "recovery matrix machine marker"
check_contains "$SOURCE_CONTENT" "scenario=%@" "recovery matrix scenario marker"
check_contains "$SOURCE_CONTENT" "section=recovery-matrix" "support bundle recovery matrix section marker"
check_contains "$SOURCE_CONTENT" "copyRecoveryReportDiagnostic:" "recovery report diagnostic action"
check_contains "$SOURCE_CONTENT" "recoveryReportDiagnosticText" "recovery report diagnostic text helper"
check_contains "$SOURCE_CONTENT" "diagnostics/recovery-report" "recovery report diagnostic URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/recovery-report" "recovery report diagnostic docs"
check_contains "$SOURCE_CONTENT" "recoveryReport=1" "recovery report machine marker"
check_contains "$SOURCE_CONTENT" "summary=%@" "recovery report summary marker"
check_contains "$SOURCE_CONTENT" "coverage=%ld/%ld" "recovery report coverage marker"
check_contains "$SOURCE_CONTENT" "missingScenarios=%@" "recovery report missing scenarios marker"
check_contains "$SOURCE_CONTENT" "suggestionCount=%ld" "recovery report suggestion marker"
check_contains "$SOURCE_CONTENT" "section=recovery-report" "support bundle recovery report section marker"
check_contains "$SOURCE_CONTENT" "排查中心" "diagnostic center menu"
check_contains "$SOURCE_CONTENT" "copyIssueBundleDiagnostic:" "issue bundle diagnostic action"
check_contains "$SOURCE_CONTENT" "issueBundleDiagnosticText" "issue bundle diagnostic text helper"
check_contains "$SOURCE_CONTENT" "diagnostics/issue-bundle" "issue bundle diagnostic URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/issue-bundle" "issue bundle diagnostic docs"
check_contains "$SOURCE_CONTENT" "issueBundle=1" "issue bundle machine marker"
check_contains "$SOURCE_CONTENT" "issueTemplate=1" "issue template machine marker"
check_contains "$SOURCE_CONTENT" "section=issue-template" "issue template section marker"
check_contains "$SOURCE_CONTENT" "请先在菜单栏选择「排查中心」->「复制问题反馈包」" "issue feedback template prompt"
check_contains "$SOURCE_CONTENT" "copySupportBundleDiagnostic:" "support bundle diagnostic action"
check_contains "$SOURCE_CONTENT" "supportBundleDiagnosticText" "support bundle diagnostic text helper"
check_contains "$SOURCE_CONTENT" "diagnostics/support-bundle" "support bundle diagnostic URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/support-bundle" "support bundle diagnostic docs"
check_contains "$SOURCE_CONTENT" "supportBundle=1" "support bundle machine marker"
check_contains "$SOURCE_CONTENT" "section=display" "support bundle display section marker"
check_contains "$SOURCE_CONTENT" "section=calendar" "support bundle calendar section marker"
check_contains "$SOURCE_CONTENT" "runDisplayChangeTraceSelfCheck:" "display change trace self check action"
check_contains "$SOURCE_CONTENT" "diagnostics/display-change-trace" "display change trace automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/display-change-trace" "display change trace docs"
check_contains "$SOURCE_CONTENT" "displayChangeFrom=" "display change trace previous marker"
check_contains "$SOURCE_CONTENT" "displayChangeTo=" "display change trace current marker"
check_contains "$SOURCE_CONTENT" "diagnostics/display-live" "real display check automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/display-live" "real display check docs"
check_contains "$SOURCE_CONTENT" "真实显示环境自检" "real display diagnostics"
check_contains "$SOURCE_CONTENT" "runOverlayYieldStressTest:" "overlay yield stress action"
check_contains "$SOURCE_CONTENT" "diagnostics/overlay-yield" "overlay yield automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/overlay-yield" "overlay yield docs"
check_contains "$SOURCE_CONTENT" "窗口让开压测" "overlay yield diagnostics"
check_contains "$SOURCE_CONTENT" "runWindowLayerPolicyStressTest:" "window layer policy stress action"
check_contains "$SOURCE_CONTENT" "diagnostics/window-layer" "window layer policy automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/window-layer" "window layer policy docs"
check_contains "$SOURCE_CONTENT" "窗口层级压测" "window layer policy diagnostics"
check_contains "$SOURCE_CONTENT" "runAutomationPolicyStressTest:" "automation policy stress action"
check_contains "$SOURCE_CONTENT" "diagnostics/automation-policy" "automation policy automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/automation-policy" "automation policy docs"
check_contains "$SOURCE_CONTENT" "安静时段只发通知" "quiet hours notification-only diagnostic"
check_contains "$SOURCE_CONTENT" "自动暂停已关闭休息页" "auto pause closes rest window diagnostic"
check_contains "$SOURCE_CONTENT" "提醒时间已顺延" "auto pause shifts timer diagnostic"
check_contains "$SOURCE_CONTENT" "runPresentationPolicyStressTest:" "presentation policy stress action"
check_contains "$SOURCE_CONTENT" "diagnostics/presentation-policy" "presentation policy automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/presentation-policy" "presentation policy docs"
check_contains "$SOURCE_CONTENT" "演示模式只发通知" "presentation policy notification-only diagnostic"
check_contains "$SOURCE_CONTENT" "演示命中已关闭休息页" "presentation policy closes rest window diagnostic"
check_contains "$SOURCE_CONTENT" "恢复自检不弹休息页" "presentation policy recovery diagnostic"
check_contains "$SOURCE_CONTENT" "runRealPresentationPolicyCheck:" "real presentation policy check action"
check_contains "$SOURCE_CONTENT" "diagnostics/presentation-live" "live presentation policy check URL"
check_contains "$SOURCE_CONTENT" "真实演示联动自检" "live presentation policy check diagnostic"
check_contains "$README_CONTENT" "songyixia://diagnostics/presentation-live" "live presentation policy check docs"
check_contains "$SOURCE_CONTENT" "runCalendarPolicyStressTest:" "calendar policy stress action"
check_contains "$SOURCE_CONTENT" "diagnostics/calendar-policy" "calendar policy automation URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/calendar-policy" "calendar policy docs"
check_contains "$SOURCE_CONTENT" "日历会议只发通知" "calendar focus notification-only diagnostic"
check_contains "$SOURCE_CONTENT" "日程暂停已关闭休息页" "calendar auto-pause closes rest window diagnostic"
check_contains "$SOURCE_CONTENT" "统计已还原" "calendar policy stats restore diagnostic"
check_contains "$SOURCE_CONTENT" "copyCalendarDiagnostic:" "calendar diagnostic action"
check_contains "$SOURCE_CONTENT" "calendarDiagnosticText" "calendar diagnostic text helper"
check_contains "$SOURCE_CONTENT" "diagnostics/calendar-real" "real calendar diagnostic URL"
check_contains "$README_CONTENT" "songyixia://diagnostics/calendar-real" "real calendar diagnostic docs"
check_contains "$SOURCE_CONTENT" "runRealCalendarPolicyCheck:" "real calendar policy check action"
check_contains "$SOURCE_CONTENT" "diagnostics/calendar-live" "live calendar policy check URL"
check_contains "$SOURCE_CONTENT" "真实日历联动自检" "live calendar policy check diagnostic"
check_contains "$README_CONTENT" "songyixia://diagnostics/calendar-live" "live calendar policy check docs"
check_contains "$SOURCE_CONTENT" "反馈问题" "issue feedback menu"
check_contains "$SOURCE_CONTENT" "NSURLComponents" "issue URL builder"
check_contains "$SOURCE_CONTENT" "NSURLSession" "update check network request"
check_contains "$SOURCE_CONTENT" "ERCompareVersionStrings" "version comparison helper"
check_contains "$SOURCE_CONTENT" "ERSettingsRestWindowTopmostKey: @NO" "rest window topmost default"
check_contains "$SOURCE_CONTENT" "置顶强提醒" "topmost reminder setting"
check_contains "$SOURCE_CONTENT" "restOverlayYielded" "yielded rest overlay state"
check_contains "$SOURCE_CONTENT" "yieldRestOverlayForUserFocusChange" "rest overlay yield helper"
check_contains "$SOURCE_CONTENT" "窗口让开" "rest overlay yield diagnostic"
check_contains "$SOURCE_CONTENT" "窗口让开压测" "overlay yield stress diagnostic"
check_contains "$SOURCE_CONTENT" "测试状态已还原" "stress tests restore state marker"
check_contains "$SOURCE_CONTENT" "窗口让开状态已还原" "overlay yield restore marker"
check_contains "$SOURCE_CONTENT" "窗口层级状态已还原" "window layer restore marker"
check_contains "$SMOKE_CONTENT" "窗口让开状态已还原" "overlay yield restore smoke wait"
check_contains "$SMOKE_CONTENT" "窗口层级状态已还原" "window layer restore smoke wait"
check_contains "$SOURCE_CONTENT" "applicationDidResignActive:" "rest overlay app resign yield"
check_contains "$SOURCE_CONTENT" "normalizeWindowLevelsForCurrentSettings" "window level normalization"
check_contains "$SOURCE_CONTENT" "demoteSettingsWindowAfterResignActive" "settings window demotion"
check_contains "$SOURCE_CONTENT" "NSArray<NSView *> *interactiveViews" "rest overlay blank-area yield"
check_contains "$SOURCE_CONTENT" "- (void)sendEvent:(NSEvent *)event" "rest overlay first-click event handling"
check_contains "$SOURCE_CONTENT" "- (BOOL)acceptsFirstMouse:(NSEvent *)event" "rest overlay accepts first mouse"
check_contains "$SOURCE_CONTENT" "ERRestOverlayContentView" "rest overlay first-click content view"
check_contains "$SOURCE_CONTENT" "ERRestActionButton" "rest overlay first-click action buttons"
check_contains "$SOURCE_CONTENT" "actionButtonWithTitle:" "rest overlay action button factory"
check_contains "$SOURCE_CONTENT" "已模拟休息页按钮链路异常" "rest action binding stress simulation"
check_contains "$SOURCE_CONTENT" "按钮链路已修复" "rest action binding recovery diagnostic"
check_contains "$SOURCE_CONTENT" "恢复压测状态已还原" "recovery stress restore marker"
check_contains "$SMOKE_CONTENT" "recovery stress did not repair broken action bindings" "rest action binding smoke check"
check_contains "$SOURCE_CONTENT" "cleanupDiagnosticEyeRest" "diagnostic rest cleanup helper"
check_contains "$SOURCE_CONTENT" "休息页尺寸不匹配当前屏幕，已重新贴合" "rest overlay bounds refit diagnostic"
check_contains "$README_CONTENT" "卡片空白、背景" "non-topmost rest overlay docs"
[[ "$SOURCE_CONTENT" == *"@interface ERSettingsWindow : NSWindow"* ]] || fail "settings window must remain a normal NSWindow"
[[ "$SOURCE_CONTENT" == *"window.level = NSNormalWindowLevel;"* ]] || fail "settings window must use NSNormalWindowLevel"
if [[ "$SOURCE_CONTENT" =~ NSFloatingWindowLevel|floatingPanel|NSWindowStyleMaskUtilityWindow|@interface\ ERSettingsPanel\ :\ NSPanel ]]; then
  fail "settings window floating-panel regression detected"
fi
REST_PRESENT_BLOCK="$(awk '/- \(void\)presentOverlay /{inside=1} inside && /^}/ {print; exit} inside{print}' "$SOURCE_FILE")"
check_contains "$REST_PRESENT_BLOCK" "if (self.appDelegate.settings.restWindowTopmost)" "rest overlay topmost gate"
check_contains "$REST_PRESENT_BLOCK" "[self.window orderFront:nil];" "rest overlay non-topmost presentation"
if [[ "$REST_PRESENT_BLOCK" != *"restWindowTopmost"* || "$REST_PRESENT_BLOCK" == *"[self.window orderFrontRegardless];"* && "$REST_PRESENT_BLOCK" != *"if (self.appDelegate.settings.restWindowTopmost)"* ]]; then
  fail "rest overlay orderFrontRegardless must stay gated by restWindowTopmost"
fi
REST_INIT_BLOCK="$(awk '/- \(instancetype\)initWithAppDelegate:/{inside=1} inside && /return self;/{print; exit} inside{print}' "$SOURCE_FILE")"
check_contains "$REST_INIT_BLOCK" "window.collectionBehavior = NSWindowCollectionBehaviorManaged;" "rest overlay default collection behavior"
if [[ "$REST_INIT_BLOCK" == *"NSWindowCollectionBehaviorCanJoinAllSpaces"* || "$REST_INIT_BLOCK" == *"NSWindowCollectionBehaviorFullScreenAuxiliary"* ]]; then
  fail "rest overlay must not join all spaces by default"
fi
ENSURE_REST_BLOCK="$(awk '/- \(void\)ensureRestWindowForKind:/{inside=1} inside && /^}/ {print; exit} inside{print}' "$SOURCE_FILE")"
if [[ "$ENSURE_REST_BLOCK" == *"settingsWindowController close"* ]]; then
  fail "rest overlay must not close settings window when presenting"
fi
BEGIN_REST_BLOCK="$(awk '/- \(void\)beginRestForKind:/{inside=1} inside && /^}/ {print; exit} inside{print}' "$SOURCE_FILE")"
if [[ "$BEGIN_REST_BLOCK" == *"settingsWindowController close"* ]]; then
  fail "manual rest must not close settings window when presenting"
fi
SETTINGS_PRESENT_BLOCK="$(awk '/- \(void\)presentSettingsWindow /{inside=1} inside && /}/{print; exit} inside{print}' "$SOURCE_FILE")"
check_contains "$SOURCE_CONTENT" "settingsWindow.level = NSNormalWindowLevel;" "settings window normal level on present"
check_contains "$SOURCE_CONTENT" "settingsWindow.collectionBehavior = NSWindowCollectionBehaviorManaged;" "settings window managed behavior on present"
if [[ "$SETTINGS_PRESENT_BLOCK" == *"orderFrontRegardless"* ]]; then
  fail "settings window must not use orderFrontRegardless"
fi

echo "==> Verifying signature and diagnostics"
codesign --verify --deep --strict "$APP_BUNDLE"
CODESIGN_DETAILS="$(codesign -dv "$APP_BUNDLE" 2>&1 || true)"
[[ "$CODESIGN_DETAILS" == *"Signature=adhoc"* ]] || fail "expected ad-hoc signature"
DIAGNOSE_OUTPUT="$(APP_TARGET="$APP_BUNDLE" scripts/diagnose_app.sh)"
[[ "$DIAGNOSE_OUTPUT" =~ codesign[[:space:]]verify:[[:space:]]+ok ]] || fail "diagnostics did not confirm signature"
[[ "$DIAGNOSE_OUTPUT" == *"== Display Recovery =="* ]] || fail "diagnostics missing display recovery section"
[[ "$DIAGNOSE_OUTPUT" == *"songyixia://diagnostics/issue-bundle"* ]] || fail "diagnostics missing issue bundle URL"
[[ "$DIAGNOSE_OUTPUT" == *"songyixia://diagnostics/display-real"* ]] || fail "diagnostics missing display diagnostic URL"
[[ "$DIAGNOSE_OUTPUT" == *"songyixia://diagnostics/settings-window"* ]] || fail "diagnostics missing settings recovery URL"
[[ "$DIAGNOSE_OUTPUT" == *"songyixia://diagnostics/display-change-trace"* ]] || fail "diagnostics missing display trace URL"
[[ "$DIAGNOSE_OUTPUT" == *"== Recovery Matrix =="* ]] || fail "diagnostics missing recovery matrix section"
[[ "$DIAGNOSE_OUTPUT" == *"songyixia://diagnostics/recovery-matrix"* ]] || fail "diagnostics missing recovery matrix URL"
[[ "$DIAGNOSE_OUTPUT" == *"songyixia://diagnostics/recovery-report"* ]] || fail "diagnostics missing recovery report URL"
[[ "$DIAGNOSE_OUTPUT" == *"songyixia://diagnostics/recovery-matrix-suite"* ]] || fail "diagnostics missing recovery matrix suite URL"
[[ "$DIAGNOSE_OUTPUT" == *"songyixia://diagnostics/window-layer"* ]] || fail "diagnostics missing window layer matrix URL"

echo "==> Verifying changelog"
grep -q "## $EXPECTED_VERSION" CHANGELOG.md || fail "CHANGELOG.md missing $EXPECTED_VERSION section"

echo "==> Packaging app"
ARCHIVE="$(scripts/package_app.sh)"
[[ -s "$ARCHIVE" ]] || fail "archive was not created"
ZIP_LIST="$(unzip -l "$ARCHIVE")"
[[ "$ZIP_LIST" == *"Contents/MacOS/EyeRest"* ]] || fail "archive missing executable"
[[ "$ZIP_LIST" == *"Contents/Resources/AppIcon.icns"* ]] || fail "archive missing icon"
if [[ "$ZIP_LIST" == *"/._"* ]]; then
  fail "archive contains AppleDouble resource files"
fi

echo "==> Verifying packaged app"
TMPDIR_RELEASE="$(mktemp -d "${TMPDIR:-/tmp}/songyixia-release.XXXXXX")"
cleanup() {
  rm -rf "$TMPDIR_RELEASE"
}
trap cleanup EXIT
ditto -x -k "$ARCHIVE" "$TMPDIR_RELEASE"
codesign --verify --deep --strict "$TMPDIR_RELEASE/松一下.app"
PACKAGED_DIAGNOSE_OUTPUT="$(APP_TARGET="$TMPDIR_RELEASE/松一下.app" scripts/diagnose_app.sh)"
[[ "$PACKAGED_DIAGNOSE_OUTPUT" =~ codesign[[:space:]]verify:[[:space:]]+ok ]] || fail "packaged app diagnostics failed"

echo "==> Preflight passed: $ARCHIVE"
